# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20160821_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='playlist.Song'),
        ),
    ]
