# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20160828_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='artistsource',
            name='external_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='playlist.Playlist'),
        ),
        migrations.AlterField(
            model_name='songsource',
            name='external_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
