# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_auto_20160828_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsource',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='playlist.Artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songsource',
            name='song',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='playlist.Song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=201),
        ),
    ]
