# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_auto_20160905_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='playlist.Artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artistsource',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_id', to='playlist.Artist'),
        ),
    ]
